git:
    depth: 1
language: python
cache:
    pip: true
matrix:
    include:
        - python: "3.4"
          # pytest 2.8 supports
          env: PYTEST_VERSION='==2.8.0' NUMPY_VERSION='==1.7' MATPlOTLIB_VERSION='==1.5.0'
        - python: "3.6"
          env: PYTEST_VERSION= NUMPY_VERSION= MATPLOTLIB_VERSION= # latest.
install: # force installation order.
    - |
        for req in pytest"$PYTEST_VERSION" codecov pytest-cov numpy"$NUMPY_VERSION" matplotlib"$MATPLOTLIB_VERSION" .; do
            pip install $req
        done
script: py.test --cov
after_success: codecov
