git:
  depth: 1
dist: xenial
sudo: true
language: python
cache:
  pip: true
matrix:
  include:
  - python: "3.6"
    env: |
      PYTEST_VERSION='==3.7.1'
      PYTEST_COV_VERSION='==2.9.0'
      NUMPY_VERSION='==1.11'
      MATPLOTLIB_VERSION='==3.1.0'
  - python: "3.6"
  - python: "3.7"
  - python: "3.8"
  - python: "3.9"
install: |
  pip install --upgrade pip pytest"$PYTEST_VERSION" pytest-cov"$PYTEST_COV_VERSION" codecov &&
  # Force install of numpy before matplotlib.
  pip install --upgrade --upgrade-strategy=only-if-needed numpy"$NUMPY_VERSION" &&
  pip install --upgrade --upgrade-strategy=only-if-needed matplotlib"$MATPLOTLIB_VERSION" &&
  pip install . &&
  pip list
script: pytest --cov
after_success: codecov
